language: node_js
sudo: required
node_js:
 - "node"
services:
 - docker
env:
  - DOCKER_COMPOSE_VERSION=1.21.2
before_install:
- docker pull elasticsearch
stages:
- name: build
jobs:
  include:
    - stage: build
      script:
        - docker build -t elasticsearch .
        - docker-compose up --build

  
 
